const router = require('express').Router()
const tasks = require('./tasks.routes')
const classes = require('./classes.routes')
const users = require('./users.routes')
const schools = require('./schools.routes')
const homeworkgrade = require('./homeworkgrade.routes')
const materias = require('./materias.routes')
const auth = require('./auth.routes')
const actions = require('./actions.routes')
const modules = require('./modules.routes')
const roles = require('./roles.routes')
const access = require('./access.routes')
const publications = require('./publications.route')
const cicloElectivos = require('./cicloElectivos.routes')
const matriculas = require('./matriculas.routes')

const load = require('./load.routes')
const file = require('./files.routes')
const cicloLectivos = require('./cicloElectivos.routes')
const teacherMaterias = require('./teacherMaterias.routes')

router.use('/tasks', tasks)
router.use('/users', users)
router.use('/roles', roles)
router.use('/classes', classes)
router.use('/auth', auth)
router.use('/schools', schools)
router.use('/homeworkgrade', homeworkgrade)
router.use('/materias', materias)
router.use('/actions', actions)
router.use('/modules', modules)
router.use('/access', access)
router.use('/publications', publications)
router.use('/cicloElectivos', cicloElectivos)
router.use('/matriculas', matriculas)
router.use('/load', load)
router.use('/file', file)
router.use('/cicloElectivos', cicloLectivos)
router.use('/teacherMaterias', teacherMaterias)

module.exports = router
