const users = [
  {
    firstName: 'Wilmer',
    lastName: 'Ortiz',
    userName: 'wilmer.user',
    birthdate: '1988-11-02',
    identification: '1231233',
    email: 'wilmer@hotmail.com',
    password: '1234',
  },
  {
    firstName: 'Nicolas',
    lastName: 'Liasso',
    userName: 'nico.user',
    birthdate: '1999-11-02',
    identification: '11231234',
    email: 'nico@hotmail.com',
    password: '12345',
  },
  {
    firstName: 'Valentin',
    lastName: 'Campos',
    userName: 'valen.user',
    birthdate: '1999-11-02',
    identification: '12312335',
    email: 'vale@hotmail.com',
    password: '12346',
  },
  {
    firstName: 'Luan',
    lastName: 'Klett',
    userName: 'luan.user',
    birthdate: '1999-11-02',
    identification: '12312336',
    email: 'luan@hotmail.com',
    password: '12347',
  },
  {
    firstName: 'Jose',
    lastName: 'Sanchez',
    userName: 'jose.user',
    birthdate: '1999-11-02',
    identification: '12312337',
    email: 'jose@hotmail.com',
    password: '12347',
  },
  {
    firstName: 'Edwin',
    lastName: 'Arias',
    userName: 'edwin.user',
    birthdate: '1988-11-02',
    identification: '12312338',
    email: 'edwin@hotmail.com',
    password: '12348',
  },
  {
    firstName: 'Leandro',
    lastName: 'Villafuerte',
    userName: 'leandro.user',
    birthdate: '1999-11-02',
    identification: '12312339',
    email: 'leandro@hotmail.com',
    password: '12349',
  },
]

module.exports = { users }
